/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FTP_H_RPCGEN
#define _FTP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char buffer[25000];
	int size;
};
typedef struct data data;


struct Path {
	char FileName[20];
};
typedef struct Path Path;


#define FTPServerProgram 0x20000001
#define version1 1

#if defined(__STDC__) || defined(__cplusplus)
#define initialzeDownload 1
extern  int * initialzedownload_1(Path *, CLIENT *);
extern  int * initialzedownload_1_svc(Path *, struct svc_req *);
#define initialzeUpload 2
extern  void * initialzeupload_1(Path *, CLIENT *);
extern  void * initialzeupload_1_svc(Path *, struct svc_req *);
#define getFile 3
extern  data * getfile_1(void *, CLIENT *);
extern  data * getfile_1_svc(void *, struct svc_req *);
#define putFile 4
extern  void * putfile_1(data *, CLIENT *);
extern  void * putfile_1_svc(data *, struct svc_req *);
#define changeDirectory 5
extern  int * changedirectory_1(Path *, CLIENT *);
extern  int * changedirectory_1_svc(Path *, struct svc_req *);
#define listDirectory 6
extern  int * listdirectory_1(Path *, CLIENT *);
extern  int * listdirectory_1_svc(Path *, struct svc_req *);
#define removeFile 7
extern  int * removefile_1(Path *, CLIENT *);
extern  int * removefile_1_svc(Path *, struct svc_req *);
extern int ftpserverprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define initialzeDownload 1
extern  int * initialzedownload_1();
extern  int * initialzedownload_1_svc();
#define initialzeUpload 2
extern  void * initialzeupload_1();
extern  void * initialzeupload_1_svc();
#define getFile 3
extern  data * getfile_1();
extern  data * getfile_1_svc();
#define putFile 4
extern  void * putfile_1();
extern  void * putfile_1_svc();
#define changeDirectory 5
extern  int * changedirectory_1();
extern  int * changedirectory_1_svc();
#define listDirectory 6
extern  int * listdirectory_1();
extern  int * listdirectory_1_svc();
#define removeFile 7
extern  int * removefile_1();
extern  int * removefile_1_svc();
extern int ftpserverprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_Path (XDR *, Path*);
extern  bool_t xdr_Path (XDR *, Path*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_data ();
extern bool_t xdr_Path ();
extern bool_t xdr_Path ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FTP_H_RPCGEN */
